### ISSUE TITLE
odd gif_name in the dataset

### ISSUE THREAD

**Issue by dandelin** [YunseokJANG/tgif-qa#1]
line 24944 of Train_count_question.csv has peculiar gif_name and I couldn't find it in TGIF-Release dataset.

`tumblr_npCOUNT7hA9g1utewr4o1_250	How many times does the man look around ?	0	COUNT28222	7569`

**Comment by dandelin** [comment]
found several more in Train_count_question.csv

line 7762
`tumblr_nCOUNT1aJHx11u7wd1po1_250	How many times does the woman swing her hips ?	3	COUNT8771	35737`

line 20591
`tumblr_nCOUNTogvTYa1unyhx2o1_400	How many times does the man adjust tie ?	0	COUNT23292	78314`

**Comment by dandelin** [comment]
I found that total 12 lines have filename containing COUNT after searching Total_count_question.csv with regex `tumblr_.*COUNT.*_`.

And no such pattern appeared in other three qa category.

**Comment by YunseokJANG** [comment]
@dandelin 
Thanks for your interest in our project. I re-inspect all the codes and found similar issues on the 'count' set also. 
I replaced all the problematic files, so please rematch GIF files in TGIF dataset with the new commit c1a41b1 . Sorry for your inconvenience.
