### ISSUE TITLE
Alternative way to download the dataset?

### ISSUE THREAD

**Issue by zhangyuygss** [YunseokJANG/tgif-qa#13]
Hey, is there an alternative way to download the dataset (e.g. separate it into several part)? Downloading a 123G file from google drive is really frustrating for the network problem.
By the way, does the file in the google drive contain the newly added GIFs you mentioned in the README file? Or maybe you only added QA pairs on fixed GIFs?

**Comment by YunseokJANG** [comment]
Hi @zhangyuygss ,
Thanks for your interest in our dataset.

For the GIF files, I am serving the same GIFs as the original TGIF dataset have, so you may check the link from there also; I personally recommend you to download via a [Google Drive CLI client](https://github.com/prasmussen/gdrive).  By the way, I cannot guess what "newly added GIF" means in here, but I can sure that all the GIFs that I've used for generating this dataset is in there (and again, it is a subset of original TGIF dataset).

Best,
Yunseok

**Comment by RyanLiut** [comment]
Hi, how can I find the google drive? Thanks.
