### ISSUE TITLE
Where can I get the 'tgif-new-group.tsv' file?

### ISSUE THREAD

**Issue by wu-shuqi** [YunseokJANG/tgif-qa#20]

**Comment by YunseokJANG** [comment]
Hi, @wu-shuqi .
Thanks for your interest in our dataset. We once created that for intermediate data processing, but we don't have that file, and it is not part of the official dataset release. Instead, we shared the final [h5](https://github.com/YunseokJANG/tgif-qa/tree/master/code#pre-processing-the-visual-features), [gifs](https://github.com/YunseokJANG/tgif-qa/tree/master/dataset#downloading-gif-files) and [tsv](https://github.com/YunseokJANG/tgif-qa/tree/master/dataset) files. If you want to have a similar file in your data processing pipeline, then I think you can create your own by using those files (I am not sure whether you need this or not, by the way). I hope this comment helps.

Regards,
- Yunseok Jang

**Comment by wu-shuqi** [comment]
Thanks
