### ISSUE TITLE
Could you release the code with the current version tensorflow.

### ISSUE THREAD

**Issue by lixiangpengcs** [YunseokJANG/tgif-qa#5]
Tensorflow v0.10 is quite old for now. It is hard to set v0.10 tensorflow environment. Could you release the code of current version tensorflow just like tensorflow v1.3.0 or 1.4.0. Thank you.

**Comment by YunseokJANG** [comment]
Hi, @lixiangpengcs.
Thank you for your interest and suggestions on our project. 

Currently, we do not have the code for TF v1.x. However, since we are thinking about writing a journal with additional details, we may be able to update our code base once the submission is underway.

Best,
Yunseok

**Comment by idansc** [comment]
Sorry for bringing this back up, is there any update regarding this question? cuda7.5 is a very old legacy for most servers. 
Thanks!

**Comment by YunseokJANG** [comment]
Thanks for your reminder, @idansc .
I understand that playing with an older version of API is not a fun thing (You may able to avoid some CUDA issues by using anaconda). However, we are still working on a journal version, unfortunately. We will update once it is finalized (but I am not sure when it will be).

Best,
Yunseok
