### ISSUE TITLE
안녕하세요, 코드를 실행해 보려고 하다가 문제가 생겨서 연락드립니다.

### ISSUE THREAD

**Issue by Ign0reLee** [YunseokJANG/tgif-qa#9]
안녕하세요, Tgif-qa 논문을 읽고, 코드를 직접 돌려보고자 하는 학생입니다.

DataSet을 받고, 환경을 똑같이 만들었다고 생각해서

Training을 돌리려고 했었는데, flag부분에서 막혀서 연락드립니다.

flag에서 image_feature_net부분에서, Unknown command 에러가 발생하는데, 해결할 수 있는 방법이 있을까요?

답변 주시면 감사하겠습니다. ( _ _)

**Comment by Ign0reLee** [comment]
$ python main.py --task=Count --name=Tp
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    Model.add_flags(FLAGS)
  File "/home/cvml/tgif-qa-master/code/gifqa/models/count_models.py", line 45, in add_flags
    FLAGS.image_feature_net = "c3d"
  File "/home/cvml/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/home/cvml/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 498, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/home/cvml/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'image_feature_net'


에러 메세지 부분을 넣지 않아서 후첨 합니다. 감사합니다.

**Comment by YunseokJANG** [comment]
First of all, thanks for your interest in our dataset. 
I guess you didn't check [this folder](https://github.com/YunseokJANG/tgif-qa/tree/master/code/gifqa/test_scripts). There is a couple of scripts with appropriate flags. Please check those scripts and take appropriate flags if you want to train your own model. (I know that these are for testing, but you can remove the checkpoint_path and the testing flag if you want to train from scratch) ;)

Regards,
Yunseok

**Comment by Ign0reLee** [comment]
답변 감사합니다. 아직 영어가 짧아, 한글로 계속 문의하는 점 죄송합니다.

혹시 텐서플로 버전이 더 상위 버전에서는 안돌아가는 이슈가 있나요?

**Comment by YunseokJANG** [comment]
Yes, you should run this code on TensorFlow v0.10.0. 
Please check the guide in [here](https://github.com/YunseokJANG/tgif-qa/blob/master/code/README.md)

**Comment by Ign0reLee** [comment]
감사합니다. 

현재 머신이 RTX라 CUDA를 더 하위 버전으로 내릴 순 없을 것 같아서 해결은 조금 늦게 봐야할 것 같네요 다른 머신이 준비되는대로 확인 후 해결 되면 코멘트 남기겠습니다.

다시한번 감사드립니다.
